# Generated by Django 4.2.7 on 2023-12-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
